#!/usr/bin/env python3
"""
Generate C++ watchpoint registration code from config/memory_map.toml.

The memory map is authored in TOML (human-readable, versioned with the
project). The PS2 runtime watchpoint registry needs plain C++ calls to
`ps2wp::add(addr, width, label)`. This tool bridges the two by emitting a
generated header the bootstrap can include.

Usage:
    python tools/gen_watchpoints.py \\
        --memory-map config/memory_map.toml \\
        --output src/generated/memory_map_watchpoints.h

Then in main.cpp:
    #include "memory_map_watchpoints.h"
    ...
    register_all_memory_map_watchpoints();            // everything
    register_memory_map_watchpoints({"state_machine", "gs_state"});  // by tag
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

try:
    import tomllib  # Python 3.11+
except ImportError:
    import tomli as tomllib  # type: ignore


def sanitize(s: str) -> str:
    # C-identifier-safe string for comments / quotes.
    return s.replace('"', '\\"')


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--memory-map", required=True)
    ap.add_argument("--output",     required=True)
    args = ap.parse_args()

    mmap = Path(args.memory_map)
    if not mmap.exists():
        sys.exit(f"memory_map not found: {mmap}")
    with open(mmap, "rb") as f:
        data = tomllib.load(f)

    entries = data.get("entries", [])

    out_lines: list[str] = []
    out_lines.append("// AUTO-GENERATED by tools/gen_watchpoints.py — do not edit by hand.")
    out_lines.append(f"// Source: {mmap}")
    out_lines.append("// Registers entries from config/memory_map.toml as runtime watchpoints.")
    out_lines.append("//")
    out_lines.append("// The file is regenerated each time the TOML changes. Check it in so")
    out_lines.append("// main.cpp can include it without needing a TOML parser in the runtime.")
    out_lines.append("")
    out_lines.append("#pragma once")
    out_lines.append("")
    out_lines.append("#include \"ps2_watchpoints.h\"")
    out_lines.append("#include <string>")
    out_lines.append("#include <unordered_set>")
    out_lines.append("")
    out_lines.append("namespace memory_map_generated {")
    out_lines.append("")

    # Emit an entry struct vector once.
    out_lines.append("struct MapEntry {")
    out_lines.append("    std::uint32_t addr;")
    out_lines.append("    std::uint32_t width;")
    out_lines.append("    const char*   name;")
    out_lines.append("    const char*   desc;")
    out_lines.append("    const char*   tags_csv;  // comma-separated")
    out_lines.append("};")
    out_lines.append("")
    out_lines.append("inline const MapEntry kEntries[] = {")

    parsed = 0
    skipped_no_addr = 0
    for entry in entries:
        addr_s = entry.get("address")
        if addr_s is None:
            skipped_no_addr += 1
            continue
        try:
            addr = int(addr_s, 0) if isinstance(addr_s, str) else int(addr_s)
        except (TypeError, ValueError):
            skipped_no_addr += 1
            continue
        # Width resolution: explicit `width`, or `end - address`, or 4.
        width = entry.get("width")
        end = entry.get("end")
        if width is None and end is not None:
            try:
                end_i = int(end, 0) if isinstance(end, str) else int(end)
                width = end_i - addr
            except (TypeError, ValueError):
                width = 4
        if width is None:
            width = 4
        if isinstance(width, str):
            try:
                width = int(width, 0)
            except ValueError:
                width = 4
        name  = entry.get("name", f"addr_{addr:08x}")
        desc  = entry.get("desc", "")
        tags  = entry.get("tags", []) or []
        tags_csv = ",".join(tags) if isinstance(tags, list) else str(tags)

        out_lines.append(
            f"    {{ 0x{addr:08x}u, 0x{width:x}u, "
            f"\"{sanitize(name)}\", \"{sanitize(desc)}\", "
            f"\"{sanitize(tags_csv)}\" }},"
        )
        parsed += 1

    out_lines.append("};")
    out_lines.append("")
    out_lines.append(f"inline constexpr std::size_t kEntryCount = {parsed};")
    out_lines.append("")

    # Helpers.
    out_lines.append("inline bool entry_has_tag(const MapEntry& e, const std::string& tag) {")
    out_lines.append("    std::string csv(e.tags_csv);")
    out_lines.append("    std::size_t start = 0;")
    out_lines.append("    while (start <= csv.size()) {")
    out_lines.append("        std::size_t comma = csv.find(',', start);")
    out_lines.append("        if (comma == std::string::npos) comma = csv.size();")
    out_lines.append("        if (csv.substr(start, comma - start) == tag) return true;")
    out_lines.append("        start = comma + 1;")
    out_lines.append("    }")
    out_lines.append("    return false;")
    out_lines.append("}")
    out_lines.append("")

    # Main register functions.
    out_lines.append("inline void register_all_memory_map_watchpoints() {")
    out_lines.append("    for (const auto& e : kEntries) {")
    out_lines.append("        ps2wp::add(e.addr, e.width, e.name);")
    out_lines.append("    }")
    out_lines.append("}")
    out_lines.append("")
    out_lines.append("// Register only entries carrying ANY of the tags in `filter_tags`.")
    out_lines.append("inline void register_memory_map_watchpoints(")
    out_lines.append("    const std::unordered_set<std::string>& filter_tags) {")
    out_lines.append("    for (const auto& e : kEntries) {")
    out_lines.append("        for (const auto& t : filter_tags) {")
    out_lines.append("            if (entry_has_tag(e, t)) {")
    out_lines.append("                ps2wp::add(e.addr, e.width, e.name);")
    out_lines.append("                break;")
    out_lines.append("            }")
    out_lines.append("        }")
    out_lines.append("    }")
    out_lines.append("}")
    out_lines.append("")
    out_lines.append("} // namespace memory_map_generated")
    out_lines.append("")

    out_path = Path(args.output)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    content = "\n".join(out_lines)
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(content)

    print(f"Wrote {out_path}  ({parsed} entries, {skipped_no_addr} skipped)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
