#!/usr/bin/env python3
"""gen_stub_overrides.py

Generates `src/generated/stub_overrides_register.cpp` containing
`registerStubOverrides(PS2Runtime&)` that registers a non-throwing
return-zero handler for every function listed in TOML `[stubs]`.

The TOML's stubs route to `ps2_stubs::TODO_NAMED` which throws by
default. Each throw kills the game-loop thread and triggers a costly
restart cycle that masks downstream blockers. This script lets us bulk
override the throw with a clean -1 return (matching the post-warning-
suppression behaviour of TODO_NAMED) so boot can advance and we can
see what breaks next.

main.cpp calls `registerStubOverrides(runtime)` after
`registerAllFunctions(runtime)` and after the targeted per-function
overrides — so a manual override in main.cpp wins over the bulk
default if needed.

Idempotent. Re-run after TOML changes. Output is a real generated
file; do not edit by hand.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
TOML_PATH = REPO_ROOT / "config" / "racer_revenge.toml"
OUTPUT_PATH = REPO_ROOT / "src" / "generated" / "stub_overrides_register.cpp"

SKIP_BLOCK_RE = re.compile(r"^skip\s*=\s*\[(.*?)^\]", re.M | re.S)
STUB_NAME_RE = re.compile(r'"(sub_[0-9A-Fa-f]+)"')


def extract_stub_addresses(toml_text: str) -> list[int]:
    """Return sorted list of stub start addresses parsed from the
    `skip = [...]` block (skipped functions get TODO_NAMED stubs)."""
    m = SKIP_BLOCK_RE.search(toml_text)
    if not m:
        print("no skip block found in TOML", file=sys.stderr)
        return []
    block = m.group(1)
    addrs = set()
    for nm in STUB_NAME_RE.finditer(block):
        name = nm.group(1)
        # Format: sub_NNNNNNNN (8 hex digits)
        hex_part = name.removeprefix("sub_")
        try:
            addrs.add(int(hex_part, 16))
        except ValueError:
            print(f"  skip unparseable stub name: {name}", file=sys.stderr)
    return sorted(addrs)


def emit(output_path: Path, addrs: list[int]) -> None:
    lines = [
        "// AUTO-GENERATED by tools/gen_stub_overrides.py — do not edit.",
        "// Source: config/racer_revenge.toml `stubs = [...]`.",
        "// Each TOML stub is registered as a non-throwing return-0 handler,",
        "// overriding TODO_NAMED's throw. main.cpp calls",
        "// registerStubOverrides(runtime) AFTER registerAllFunctions to win",
        "// the registration race; targeted overrides in main.cpp run AFTER",
        "// this so they win over the default.",
        "",
        "#include \"ps2_runtime.h\"",
        "#include \"ps2_runtime_macros.h\"",
        "",
        "void registerStubOverrides(PS2Runtime& runtime)",
        "{",
        "    auto returnZero = +[](uint8_t* /*rdram*/, R5900Context* ctx, PS2Runtime* /*runtime*/) {",
        "        SET_GPR_S32(ctx, 2, 0);",
        "        ctx->pc = GPR_U32(ctx, 31);",
        "    };",
    ]
    for addr in addrs:
        lines.append(f"    runtime.registerFunction(0x{addr:x}, returnZero); // sub_{addr:08X}")
    lines.append("}")
    lines.append("")
    output_path.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    if not TOML_PATH.exists():
        print(f"missing TOML: {TOML_PATH}", file=sys.stderr)
        return 1
    text = TOML_PATH.read_text(encoding="utf-8")
    addrs = extract_stub_addresses(text)
    if not addrs:
        return 1
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    emit(OUTPUT_PATH, addrs)
    print(f"wrote {OUTPUT_PATH.relative_to(REPO_ROOT)} with {len(addrs)} stub overrides")
    return 0


if __name__ == "__main__":
    sys.exit(main())
